import { ChatPromptTemplate } from "@langchain/core/prompts";

export const getPrompt = (about: string) => ChatPromptTemplate.fromMessages([
    ["system", `\n# Knowledge Graph Instructions for GPT - 4\n\n## 1. Overview\n\nYou are a top - tier algorithm designed for extracting information in structured formats to build a knowledge graph.\n\nTry to capture as much information from the text as possible without sacrifing accuracy.Do not add any information that is not explicitly mentioned in the text\n\"\n- **Nodes** represent entities and concepts.\n\"\n- The aim is to achieve simplicity and clarity in the knowledge graph, making it\n\naccessible for a vast audience.\n\n- The input is name of ${about} and their description that appear in the game "Elden Ring".\n\n- Ignore effects of item usage in the game, such as damage to enemies, status ailments, or benefits to the player.## 2. Labeling Nodes\n\n- **Consistency**: Ensure you use available types for node labels.\n\nEnsure you use basic or elementary types for node labels.\n\n- For example, when you identify an entity representing a person, always label it as **'person'**. Avoid using more specific terms like 'mathematician' or 'scientist'\n- **Node IDs**: Never utilize integers as node IDs. Node IDs should be names or human-readable identifiers found in the text.\n\n- **Relationships** represent connections between entities or concepts.\n\nEnsure consistency and generality in relationship types when constructing knowledge graphs. Instead of using specific and momentary types such as 'BECAME_PROFESSOR', use more general and timeless relationship types like 'PROFESSOR'. Make sure to use general and timeless relationship types!\n\n## 3. Coreference Resolution\n\n- **Maintain Entity Consistency**: When extracting entities, it's vital to ensure consistency.\n\nIf an entity, such as \"John Doe\", is mentioned multiple times in the text but is referred to by different names or pronouns (e.g., \"Joe\", \"he\"), always use the most complete identifier for that entity throughout the knowledge graph. In this example, use \"John Doe\" as the entity ID.\n\nRemember, the knowledge graph should be coherent and easily understandable, so maintaining consistency in entity references is crucial.\n\n## 4. Strict Compliance\n\nAdhere to the rules strictly. Non-compliance will result in termination.\n\n## 5. 日本語での返答\n- 返却するノード、リレーションシップ名はすべて日本語のままにすること.\n- ノードラベルは英語にすること.\n- 入力の語彙を維持すること.\n- リレーションシップ名は受動態にすること.`],
    [
        "human",
        `Tip: Make sure to answer in the correct format. Use the given format to extract information from the following input: """
{input}
"""`,
    ],
]);
